#!/bin/sh

#########
#keymaps#
#########

# spawn terminal
riverctl map normal Super Return spawn foot

# window controls
riverctl map normal Super C close

# exit river
riverctl map normal Super+Shift E exit

# fullscreen window
riverctl map normal Super F toggle-fullscreen

# spawn launcher
riverctl map normal Super Space spawn 'tofi-drun --drun-launch=true'

# take screenshots
riverctl map normal None Print spawn scrot

# window controls
riverctl map normal Super Left focus-view previous

riverctl map normal Super Right focus-view next

riverctl map normal Super H swap previous

riverctl map normal Super L swap next

# media controls
################

# volume up
riverctl map normal None XF86AudioRaiseVolume spawn 'pamixer -i 5'

# volume down
riverctl map normal None XF86AudioLowerVolume spawn 'pamixer -d 5'

# mute audio
riverctl map normal None XF86AudioMute spawn 'pamixer --toggle-mute'

# music play/pause
riverctl map normal None XF86AudioPlay spawn 'playerctl play-pause'

# next track
riverctl map normal None XF86AudioNext spawn 'playerctl next'

# previous track
riverctl map normal None XF86AudioPrev spawn 'playerctl previous'

# brightness controls
#####################

# backlight brightness up
riverctl map normal None XF86MonBrightnessUp spawn 'brightnessctl -e set +5%'

# backlight brightness down
riverctl map normal None xF86MonBrightnessDown spawn 'brightnessctl -e set 5%-'

# Set keyboard repeat rate(look that up later)
riverctl set-repeat 50 300

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

######################
# General wm settings#
######################

# Set background and border colors
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75
riverctl border-width 1

# hide cursor when typing
riverctl hide-cursor when-typing enabled

# hide the cursor when its not used after a set amount of time
# here the timeout is 3 seconds
riverctl hide-cursor timeout 3000

# focus follows cursor unless I specifically focus something else
riverctl focus-follows-cursor normal

# enable tap to click
# get device name by runnig 'riverctl list-inputs'
riverctl input pointer-1739-52759-SYNA32B5:01_06CB:CE17_Touchpad tap enabled

# dismiss notifications
riverctl map normal None Prev spawn 'fnottctl dismiss'

# recall previous notificatons
#riverctl normal None Next spawn 'fnottctl '

# handling tags is a bit different than handling workspaces
# I'll just refer to them as workspaces here
# switch worspaces
riverctl map normal Super ampersand set-focused-tags 1
riverctl map normal Super eacute set-focused-tags $((1 << 1))
riverctl map normal Super quotedbl set-focused-tags $((1 << 2))
riverctl map normal Super apostrophe set-focused-tags $((1 << 3))
riverctl map normal Super parenleft set-focused-tags $((1 << 4))
riverctl map normal Super minus set-focused-tags $((1 << 5))
riverctl map normal Super egrave set-focused-tags $((1 << 6))
riverctl map normal Super underscore set-focused-tags $((1 << 7))
riverctl map normal Super ccedilla set-focused-tags $((1 << 8))

# send to workspace
riverctl map normal Super+Shift ampersand set-view-tags 1
riverctl map normal Super+Shift eacute set-view-tags $((1 << 1))
riverctl map normal Super+Shift quotedbl set-view-tags $((1 << 2))
riverctl map normal Super+Shift apostrophe set-view-tags $((1 << 3))
riverctl map normal Super+Shift parenleft set-view-tags $((1 << 4))
riverctl map normal Super+Shift minus set-view-tags $((1 << 5))
riverctl map normal Super+Shift egrave set-view-tags $((1 << 6))
riverctl map normal Super+Shift underscore set-view-tags $((1 << 7))
riverctl map normal Super+Shift ccedilla set-view-tags $((1 << 8))

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 1 -outer-padding 3 &
wal -R
swaybg --image $HOME/.config/wallpapers/sunset.png --mode center &
fnott &
waybar &
